### ISSUE TITLE
make app a PanicKit Responder for device-wide panic responses

### ISSUE THREAD

**Issue by eighthave** [x13a/Wasted#1]
Sounds like a nice app to have, lots of people have asked for such a thing.  It would be nice if it could triggered in conjunction with other apps.  PanicKit has the concept of "trigger" and "responder" app, so one panic button trigger can cause many apps to do something.  This app sounds like the perfect case for a panic responder.  You can find docs, example code, and more here:
https://guardianproject.info/code/panickit/

**Comment by x13a** [comment]
I will try, thanks)

**Comment by x13a** [comment]
Done

**Comment by eighthave** [comment]
very cool :)
