### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by hjorturth** [x13a/Wasted#11]
First things, **love** the app and have tested it on Lineage OS (Android 11) on Samsung A5, works perfectly, at least coupled with PanicKit and Tiles. 

But a couple of things I feel should be added to the ReadeMe. 
What each option "Tiles, Notification,PanicKit" does and what else the user needs to do to enable it. 
For example I had no idea what "Tiles" was until I read another Issue on this github where someone asked and you very helpfully answered. 
I've yet to understand what Broadcast does, though I managed to muddle my way through the rest on my own.  

I think the improvement should be easy and increase the user experience by a lot. 

Thanks again

**Comment by x13a** [comment]
Yes, it is always nice to have a good documentation. Thanks)

**Comment by alatorceva** [comment]
> Во-первых, **люблю** приложение и протестировал его на Lineage OS (Android 11) на Samsung A5, работает отлично, по крайней мере, в сочетании с PanicKit и плитками.
> 
> Но несколько вещей, которые я чувствую, должны быть добавлены в ReadeMe. Что делает каждый параметр "Плитки, уведомления, паникит" и что еще нужно сделать пользователю, чтобы включить его. Например, я понятия не имел, что такое "Плитки", пока не прочитал еще один вопрос на этом github, где кто-то спросил и вы очень услужливо ответили.Мне еще предстоит понять, что делает Broadcast, хотя мне удалось самостоятельно пройти через все остальное.
> 
> Я думаю, что улучшение должно быть легким и значительно улучшить пользовательский опыт.
> 
> Еще раз спасибо

**Comment by alatorceva** [comment]
Да, всегда приятно иметь хорошую документацию. Спасибо)

**Comment by x13a** [comment]
Done in recent version
