### ISSUE TITLE
Improvement idea

### ISSUE THREAD

**Issue by xyz-nobody** [x13a/Wasted#12]
Improvement idea:

- Have the possibility to know the version number (ex on f-droid the app is in error when we download it because the apk is not available anymore), and i dont know if the version on playstore it's latest.

- Be able to have a finer granularity on the N Days parameter and go down to the hour.

(e.g. have time slots, from 21h to 06h = N Hours & from 06 to 21h = N Hours) 

- Have the possibility of N Hours / Days based on a wifi.
If the smartphone does not connect to a wifi X, then after N Hours, it wipes the phone.
When a state attacker takes a phone, he puts it in the wifi airplane, and even if he doesn't, we can assume that the phone will be far away from the wifi where people usually work.

- Have the possibility to have a panic password to wipe the phone directly.

- N.B.: Unfortunately, I think that for this idea, you need a screenlocker like datawipe: http://safetyapps.zone/datawipe.html

- N:B: The screenlocker comes after the normal locker or the fingerprint unlocking.

**Comment by x13a** [comment]
> to wipe the phone directly

What do you mean?

**Comment by x13a** [comment]
> Have the possibility to know the version number (ex on f-droid the app is in error when we download it because the apk is not available anymore), and i dont know if the version on playstore it's latest.

F-Droid gets update automatically from here, on its own schedule. Play Store version is updated by me right after I make a release here.

**Comment by xyz-nobody** [comment]
------- Original Message -------

On Sunday, February 20th, 2022 at 14:27, lucky ***@***.***> wrote:

> > to wipe the phone directly
> 

> What do you mean?

Unfortunately with an application that is not a screenlocker this is not possible.

Datawipe offered a screenlocker and with two codes.

1) The code that unlocks.

2) The code that wipes.

If you put the code that wipes everything is erased.

Or else manage to differentiate which fingerprint number is used and if it is the one used to unlock that wipes the phone.
but I don't know if at the api level we can find out which fingerprint number is used.

**Comment by xyz-nobody** [comment]
Frankly your application is great.

However, would it be possible to configure the wipe after X failled attemp, not to have a warning?

**Comment by x13a** [comment]
> If you put the code that wipes everything is erased.

There is a request on "Duress password wipe". I have implemented something like this as a companion app, it will available soon.

> wipe after X failled attemp, not to have a warning

There is a BFU issue related to this. For now in BFU you have got a warning and need 2X attempts to tigger. After you need X attempts and no warning. This is how I think it is working) Anyway this functionality is moved to another app, named Sentry. From the next release it will not be available anymore in Wasted.

> don't put the right fingerprint, it is not considered as an authentication attempt.

This is how Android treats them.

**Comment by xyz-nobody** [comment]
thank you for everything it's great.

I tried Duress but couldn't figure out how to make it work with Wasted.

I write a ticket on the repo of Duress
