### ISSUE TITLE
Super app

### ISSUE THREAD

**Issue by gostaex** [x13a/Wasted#13]
Hello. The app is getting better and better. But I could not deal with the broadcast message. Sending myself a text message. Send messages via messenger. So it didn't work.
Please tell me how to use broadcast message.

**Comment by x13a** [comment]
Hello.

Broadcast is an Android functionality to communicate between apps or components. You are looking for the `Notification`. Do not forget to allow Wasted to read notifications in `Settings > Notifications > Device and app notifications`.

**Comment by x13a** [comment]
Closing on inactivity
