### ISSUE TITLE
 possibility to copy/paste the auth code

### ISSUE THREAD

**Issue by xyz-nobody** [x13a/Wasted#15]
Thanks a lot for your three applications (Sentry / Wasted & Duress) they all work great together.

Could you give us the possibility to copy/paste the auth code or customize it? 

Because when we configure it in duress or in a trigger or a notification we have to reread it several times to be sure not to make a mistake.

**Comment by x13a** [comment]
It is already on the master branch. Will be available in the next release.

**Comment by x13a** [comment]
Closing on inactivity
