### ISSUE TITLE
Possible to remove incorrect password wipe warning?

### ISSUE THREAD

**Issue by InvisibleMan101** [x13a/Wasted#16]
Hi,
I just wanted to know if it were possible to remove the incorrect password wipe feature WARNING on the lock screen?

**Comment by InvisibleMan101** [comment]
If you don't want to put it in just wondering if you can point me to the right direction within the open source code and I'll try removing myself and re-compiling. Still learning this app as much as possible. Thank you for making such a great set of privacy apps.

**Comment by xyz-nobody** [comment]
By changing Launcher for example by using Nova Launcher, there is no more warning at the Lockscreen, except after a reboot.

**Comment by x13a** [comment]
Closing on inactivity
