### ISSUE TITLE
Wipe a device when it was not unlocked for ???? days

### ISSUE THREAD

**Issue by BadGrasshopper** [x13a/Wasted#17]
Hi, I could not find an option to see/change how many days to wipe if the device has not been unlocked in "n" days.

So I looked at the source code and apparently it is in 7 days, for me 7 days is great, I just do not want to end up losing my data by not knowing how many days I can stay without unlocking my device :)

Best regards.

**Comment by x13a** [comment]
Hi, make a long click on "Wipe on inactivity" and you will see the selector.

**Comment by BadGrasshopper** [comment]
Thx :D 

I love your app, especially for me who has a degoogled phone

You could put a "Hold for more options" message in the next versions or something like that <3

**Comment by x13a** [comment]
I will think of it, thanks.
