### ISSUE TITLE
ProtonAOSP / Andorid 12 - Notification not working

### ISSUE THREAD

**Issue by RealJTG** [x13a/Wasted#19]
Hi! I tried this app on ProtonAOSP, based on Android 12 (https://protonaosp.org) with no luck.

Tiles - there are no extra tiles after app installation. I see Podcast Addict tile, Cryptocam, but not Wasted one:

![Screenshot_20220615-122810](https://user-images.githubusercontent.com/930399/173795697-2777684f-f188-4592-bef2-17c1ba5f6413.png)

Shortcut - there are no shortcuts in app's context menu either. Once again, Protonmail has one for a some reason, Wasted - no:

![Screenshot_20220615-122758](https://user-images.githubusercontent.com/930399/173796700-35348175-99c2-4172-a1bc-48193e0e2856.png) ![Screenshot_20220615-123827](https://user-images.githubusercontent.com/930399/173796692-0d993878-c618-4121-89fa-0bbc19f83eb7.png)

Notifications - Wasted should be able to read all notifications, but still nothing happens when I send auth code in Telegram.

![Screenshot_20220615-124459](https://user-images.githubusercontent.com/930399/173798753-48d90ead-a3c6-489d-8a05-6ba23910484d.png)

Broadcast - not sure, can't really check if it works. I installed Duress app, configured it as decribed here https://github.com/x13a/Duress/issues/1#issuecomment-1049458803 ... but I don't want to wipe my device ATM, and there's no extra ways to see if it really works. Like I'm entering duress code on lock screen, and the only action sould be device lock, but I'm already on the lock screen, so it's unclear if Wasted worked in this case.

(And I see no way to copy auth code to clipboard, but It was mentioned in https://github.com/x13a/Wasted/issues/15. Long press to refresh code, short - to configure triggers, so again I'm not sure if there's a problem with my OS, or it copying was not implemented)

Please tell me if I can help to debug this. Thanks :)

---

Feature request: it would be nice to have some kind of armed/disarmed switch, "dry-run" mode to ensure if Wasted is configured properly and ready to nuke everything, you haven't mistyped the auth code, notifications and all stuff are working properly etc. Wasted in "disarmed" state should still listen for triggers, but instead of wiping everything it should say "I hear you, BOOM!" :)

**Comment by x13a** [comment]
As I remember copy authentication code is not in production yet. But I may
forget about it. Dry run is when you are not ticking wipe options. Without
them only biometric will be disabled on success. Please post triggers
screenshot (tap on code).

**Comment by RealJTG** [comment]
> tap on code

Oh snap, you are right, I forgot to turn on triggers. Now everything works, except notifications. I see auth code in Viber/Telegram notifications, code is correct, but trigger doesn't fire.

**Comment by x13a** [comment]
Let's move this to https://github.com/x13a/Wasted/issues/18 . I have tried yesterday in emulator via telegram and all was working. This weekend will try on pixel and write there. I will ping you.
