### ISSUE TITLE
[Feature Request] Add option to hard brick device

### ISSUE THREAD

**Issue by GPLv3-fan** [x13a/Wasted#22]
Would it be possible to hard brick a device so that thieves cannot longer profit economically from selling it ?

I was stolen and the idea of some petty thieves selling my cellphone made me wonder if it would be possible a hard brick or at least a soft brick. In such a way, the value of the stolen cellphone would be zero.

Thanks for your great work !

**Comment by x13a** [comment]
I do not think that it can be done. Anyway this is not in the scope of this
app.

**Comment by x13a** [comment]
Closing on inactivity
