### ISSUE TITLE
Wipe On Inactivity

### ISSUE THREAD

**Issue by xyz-nobody** [x13a/Wasted#26]
On grapheneos

When I set up a time in minutes or hours and change my profile. 
nb: it also happens to me in random ways on a phone under grapheneos which has no profile. I just disconnect and when I come back it sets the default value 7D

Ex : 30 mn

I switch to a user profile, I disconnect after 35 minutes from the user profile, I reconnect to the Owner Profile.

I reopen Wasted and the default time is back to 7D.

So it didn't Wipe
On grapheneos

When I set up a time in minutes or hours and change my profile. 

Ex : 30 mn

I switch to a user profile, I disconnect after 35 minutes from the user profile, I reconnect to the Owner Profile.

I reopen Wasted and the default time is back to 7D.

So it didn't Wipe

**Comment by x13a** [comment]
To change time to 30 minutes you have to write 30m and then press the check
button.

**Comment by xyz-nobody** [comment]
thank you, perhaps it is necessary to change color so that one understands?

**Comment by x13a** [comment]
What color?

**Comment by xyz-nobody** [comment]
Ex : green if you have clicked on the button
red if not clicked with maybe a ! in warning ?

**Comment by x13a** [comment]
Will think of it, closing as resolved
