### ISSUE TITLE
Lock - Wipe for inactivity

### ISSUE THREAD

**Issue by xyz-nobody** [x13a/Wasted#29]
I tried 1m / 5m
I activated the tab but it doesn't wipe the phone automatically
nb : before the update it worked perfectly

![signal-2022-07-07-023115_005](https://user-images.githubusercontent.com/6586244/177678119-43e84429-268b-419e-98aa-6630a6d9beae.jpeg)
![signal-2022-07-07-023115_004](https://user-images.githubusercontent.com/6586244/177678115-5f5b1ca0-bf93-4700-b878-94a019b327bf.jpeg)
![signal-2022-07-07-023115_002](https://user-images.githubusercontent.com/6586244/177678108-b22394bf-47fa-45ce-aa8b-a78e7eefe262.jpeg)
![signal-2022-07-07-023115_003](https://user-images.githubusercontent.com/6586244/177678113-b0330d6f-ea7e-40f3-8623-5f36445fe0ce.jpeg)
![signal-2022-07-07-023115_001](https://user-images.githubusercontent.com/6586244/177678096-24ab1ec4-0cd2-4cfa-8d2a-3747f4adae90.jpeg)

**Comment by x13a** [comment]
Will check it soon, thank you very much)

**Comment by xyz-nobody** [comment]
thk to you.

i continu to test all possibility with wasted, 
I keep trying all the other features. I have a phone only for testing so I can wipe it 100 times :)

**Comment by xyz-nobody** [comment]
very strange, i make new test again and now the phone is wipe with 1m.

i continu test

**Comment by xyz-nobody** [comment]
I have configured 1mn

It's been 30 minutes and it still hasn't wiped.

I have the impression that if at the first boot and I stay too long not connected that it does not wipe.
Even when I log in afterwards.

**Comment by x13a** [comment]
yeah, found bug

**Comment by x13a** [comment]
hope will work now

**Comment by xyz-nobody** [comment]
thank you, everything works. Even at first boot :)

Thanks for this great software

**Comment by xyz-nobody** [comment]
Ex the phone has been turned off by an attacker for 10 days, he turns it back on so the delay starts from 0.

Is it possible that if the delay is exceeded that it wipes the phone at boot?

It works for the usb, so I hope it works for the Lock Time :)

**Comment by x13a** [comment]
> the delay starts from 0

Is this true?

**Comment by xyz-nobody** [comment]
yes but with this morning's version 1.5.2 the problem has been fixed

**Comment by x13a** [comment]
Version 1.5.2 has nothing to do with it.

**Comment by xyz-nobody** [comment]
Bizzare because the behavior has changed between version 1.5.1 & 1.5.2

Ex: With version 1.5.1 = When I was in a user profile (even logged in while doing an action), then once the lock timeout expires in the owner profile it wipes the phone.

With version 1.5.2 = When I am in a user profile (logged in while doing an action), once the lock expiry time in the owner profile is passed, it does not wipe the phone

**Comment by x13a** [comment]
OK, let's close this one. If you will find a bug, please open a new issue.
