### ISSUE TITLE
USBKill

### ISSUE THREAD

**Issue by xyz-nobody** [x13a/Wasted#30]
Under GrapheneOS

It works perfectly, even on the first boot before unlocking.

On the other hand I have noticed and I do not know if it can be fixed.

If at startup a USB cable is connected, then wasted does nothing because I think it detects a USB connection before wasted. So it doesn't wipe, but anyway we can't attack the phone like that.

So it's not a big deal, it's just for information 
you can close it, i just write this for the records

**Comment by xyz-nobody** [comment]
you solve this in same time with version 1.5.1 :) :+1:

**Comment by x13a** [comment]
Good to know that, closing as resolved
