### ISSUE TITLE
fake icon - small buble only when you use lock

### ISSUE THREAD

**Issue by xyz-nobody** [x13a/Wasted#36]
When we click on Lock it adds a small bubble in the icons.

Otherwise the icons are perfectly normal.

This trick is diabolical, thank you

sorry for the quality of the pictures the camera is not good

![1](https://user-images.githubusercontent.com/6586244/179298605-38768d67-5bd1-40f8-9f5b-1018a6df428d.jpeg)
![2](https://user-images.githubusercontent.com/6586244/179298628-86d1c390-53fb-4d30-95bd-3b42ccec6866.jpeg)
![3](https://user-images.githubusercontent.com/6586244/179298633-9ae84a9c-d05b-4a0e-a912-2b931f530dc6.jpeg)

**Comment by x13a** [comment]
Fixed in recent version, good job @xyz-nobody )
May require fresh install of Wasted.
