### ISSUE TITLE
Does it work when the phone is dead? 

### ISSUE THREAD

**Issue by Beach77** [x13a/Wasted#40]
Say I have the app set to wipe after 2 days of not being unlocked and the phone has been dead for over 2 days and I charge the phone and start it, will it still wipe or does it not count the time it was dead? 

I know this doesn't really belong here but since there is no discussion section I don't know where else to post it.

**Comment by x13a** [comment]
It has to. But better to lock it, before your device will die. Wasted
schedules the wipe task on the screen off event.

**Comment by x13a** [comment]
Closing on inactivity
