### ISSUE TITLE
samsung wasted trigger by notification

### ISSUE THREAD

**Issue by MDgit897** [x13a/Wasted#46]
Hello, using samsung device, giving all rights it asks, including notification access, it does not trigger when code is send using threema, signal or session, I check marked all 3, and tested all 3, 
is there a particular reason for that ?
It cannot work on samsung ?
USB trigger does work, 
I hope someone can help me with this, I tried many things.

**Comment by x13a** [comment]
Hello,

Plz check https://github.com/x13a/Wasted/issues/18

**Comment by MDgit897** [comment]
Hello X13a,thank you for your reply,  I checked what you send me, I had checked it before, now in samsung, you can allow notification access, but unlike pixel, you cannot check anything under it, its just you can allow notification access, and doing that does not make it work, is that a known issue ?

**Comment by MDgit897** [comment]
by the way, on my pixel works, its just the samsung galaxy a32, android 12, wher eit does not work,

**Comment by x13a** [comment]
I have Samsung tablet, will check it.

**Comment by x13a** [comment]
Should be fixed in the recent version, may require to reinstall
