### ISSUE TITLE
controller

### ISSUE THREAD

**Issue by serrq** [x13a/Wasted#52]
I would like Wasted to accept remote commands from SimpleX (simplex.chat) after successfully establishing a previous contact connection with it (see one-time link).

The commands that can be given remotely should be:

- perform a complete wipe after time based events
- perform a complete wipe after X wrong pin attempts
- lock/unlock the device
- do not accept unlock codes locally until I send the unlock code remotely (unless you enter the recovery passphrase)
- change the lock/unlock pin
- wipe esim
- turn on/off 110db siren
- send gps position once
- send gps position every X minutes
- turn on/off flashlight
- turn on/off vibration

https://github.com/simplex-chat/simplex-chat

https://simplex.chat/

https://github.com/simplex-chat/simplex-chat/issues/1065

**Comment by x13a** [comment]
It is not in the scope of this app. At least for now. Do not expect.

**Comment by x13a** [comment]
Forgot to say, you can try to lock/wipe your device with _Notification_ trigger in Wasted via sending a message with _SimpleX_.

**Comment by x13a** [comment]
Give it a try mode is when you do not check wipe data option.

**Comment by x13a** [comment]
If you do not check wipe data option your device will be force locked.
Fingerprint sensor will be disabled until you unlock it with PIN/password
or whatever method you use.

**Comment by x13a** [comment]
If you want to wipe your device when it was not unlocked for X time, you
have to use Lock trigger.

**Comment by x13a** [comment]
Firstly check Notification trigger in the Wasted settings. Then activate
Wasted and give it admin permission. After that open Menu > Notification
and press GOTO button. You will see Device & app notifications settings.
Wasted will be there.

**Comment by x13a** [comment]
As I said before on success your device will be force locked. On the lock
screen will be a text like "Device was locked by admin" and fingerprint
will be disabled.

**Comment by x13a** [comment]
>  turns yellow

Yes, it is an old useless feature. When any of triggers is checked secret code background changes color to yellow.

**Comment by x13a** [comment]
> Do you like it? Do you find it useful?

For now I have no interest in such changes.

**Comment by x13a** [comment]
I am closing it for now. If you have any questions please open a new issue.
